#!/usr/bin/env bash

ISORT_ARGS=""
CHECK_ARG=""
test -n "$STRICT" && {
  set -e
  ISORT_ARGS="--check-only --diff"
  CHECK_ARG="--check"
}

DEFAULT_CFG="${XDG_CONFIG_HOME}/pycheck/default-setup.cfg"

PYLINT_ARGS="--rcfile=${DEFAULT_CFG}"
test -f setup.cfg && PYLINT_ARGS="--rcfile=setup.cfg"
test -f pylintrc && PYLINT_ARGS="--rcfile=pylintrc"

MYPY_ARGS="--config-file=${DEFAULT_CFG}"
test -f setup.cfg && MYPY_ARGS="--config-file=setup.cfg"
test -f pylintrc && MYPY_ARGS="--config-file=pylintrc"

# clean & sort imports
echo
echo ">>>>>> pycln <<<<<<"
pycln "${@}" $CHECK_ARG
echo "-------------------"
echo
echo ">>>>>> isort <<<<<<"
isort -l100 -m3 --tc "${@}" $ISORT_ARGS
echo "-------------------"

# format
echo
echo ">>>>>> black <<<<<<"
black -l 100 "${@}" $CHECK_ARG
echo "-------------------"

# types are good
echo ">>>>>> mypy <<<<<<<"
mypy "${MYPY_ARGS}" --ignore-missing-imports --disallow-untyped-defs "${@}"
echo "-------------------"

# messy code is bad
echo
echo ">>>>>> pylint <<<<<"
pylint "${PYLINT_ARGS}" "${@}"
echo "-------------------"
